### ISSUE TITLE
Determine standards & conventions for streamlining release process

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#118]
Right now changelog updates and releases are very manual. If we can decide on some ways to standardize our workflow, hopefully we can streamline this process in the interest of releasing frequently without friction. Ideas may include using https://www.conventionalcommits.org/en/v1.0.0/ and auto-generating changelog items from commit messages. This is a new area for me so I am actively seeking input and ideas. Also if anyone is interested in taking this on, playing around with some ideas and figuring out what might be a good workflow, please feel free!

**Comment by sojeri** [comment]
I see a couple options here:

1) we could use [semantic-release](https://github.com/semantic-release/semantic-release)
2) we could use conventional-changelog + another automated release tool like [bumped](https://github.com/bumped/bumped)

Conventional changelog itself (emphasis mine) recommends using the first approach:
> It's recommended you use the high level standard-version library, which is a drop-in replacement for npm's version command, handling automated version bumping, tagging and CHANGELOG generation.
> **Alternatively, if you'd like to move towards completely automating your release process as an output from CI/CD, consider using semantic-release.**
> -- [conventional-changelog @ getting started](https://github.com/conventional-changelog/conventional-changelog#getting-started)

Using the first approach should reduce setup overhead since we'll only have to configure one tool, though beyond that I don't have any real opinions here.

@haworku how did your old team handle this?

**Comment by suzubara** [comment]
I just read through the semantic-release docs and it sounds really fun. I'm tempted to start trying to get that set up, along with commitzen or commitlint. Unless there are any objections, I would like to start doing some exploration into what an improved, automated release flow would look like and then bring the findings to a PR.

https://semantic-release.gitbook.io/semantic-release/
https://github.com/commitizen/cz-cli
https://github.com/conventional-changelog/commitlint

**Comment by haworku** [comment]
Awesome I'm excited for this and seeing how semantic-release works.  Looks promising

 @sojeri We used conventional commits on some  Lerna monorepos. Lerna has a [conventional-commits](https://github.com/lerna/lerna/blob/master/commands/version/README.md#--conventional-commits) flag (and Lerna also already handles releases).
