### ISSUE TITLE
[fix] DatePicker no `onChange` prop on input - console error 

### ISSUE THREAD

**Issue by maya** [trussworks/react-uswds#1249]
We're seeing this console error with the date picker b/c this [input](https://github.com/trussworks/react-uswds/blob/main/src/components/forms/DatePicker/DatePicker.tsx#L271) doesn't have an `onChange` prop:
```
Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
```

This error is in prod and storybook when running locally, it goes away if you just build storybook and serve from a static directory

Our implementation: https://github.com/CDCgov/prime-simplereport/pull/1609

cc @suzubara @brandonlenz

**Comment by suzubara** [comment]
hi @maya! I looked into this and it appears that previous versions of React had a [bug](https://github.com/facebook/react/issues/19323) where inputs with `onInput` but not `onChange` would cause that warning. Since the DatePicker `input` element uses `onInput`, I'm guessing that's the reason you're seeing that. Are you able to update your version of React?

**Comment by maya** [comment]
Looks like the console errors are gone after upgrading to react 17. thanks! 

/cc @nickscialli-usds
