### ISSUE TITLE
[feat] Allow for Date Format to be defined.  

### ISSUE THREAD

**Issue by d-amit** [trussworks/react-uswds#1489]
Most datepicker libraries support custom date format (YYYY-MM-DD) as the external format.  I could be mistaken but from the looks of it current implementation doesn't support this. 

some  examples...
- dd/mm/yy
- mm/dd/yy
- YYYY-MM-DD

**Comment by suzubara** [comment]
Closing this issue because the [USWDS Date picker component](https://designsystem.digital.gov/components/date-picker/) does not allow for custom date formats either, and this library is an implementation of USWDS. ReactUSWDS is not a date picker library.

**Comment by nerdstep** [comment]
@suzubara This feels like an odd stance to take. From what I can tell, USWDS is not exactly prescriptive on what the format should be.

ReactUSWDS supports internationalization, so I would imagine that a date formatted for a given locale would be a desirable feature, instead of only supporting a US-based date format.
