### ISSUE TITLE
Button should take a Component prop

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#161]
Right now, the Button component will only render a `button`. However it's very common for a user to want to implement button styles on an `<a>` element or even a custom link component (such as if they are using client-side routing). So the Button component should be modified to accept an optional `Component` prop (probably of type `ReactNode`) to support that use case. It should still default to `button` if no `Component` prop is defined.

**Comment by haworku** [comment]
@suzubara Are you satisfied with the work for #309 to cover this ticket? P

Personally I could still see us implementing a similar solution on `Button` as well. Or else exporting styles from Button to be used in Link directly with Button-like props (though that creates dependency  between the two, since props on Button can change).

**Comment by suzubara** [comment]
@haworku Yes I think this can be closed! IMO we could abstract the Button styles/classes out so they are more easily shared between the Button & Link components, but that would probably be a new issue.
