### ISSUE TITLE
feat: Add `nav` variant to Link

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#166]
We have an existing `Link` component that should be adjusted to handle a new `variant` prop called `nav`.

Requirements:
- Add `nav` as another possible value to the `StyledLinkProps` `variant` type definition
- Adjust the logic in the `linkClasses` function so that it includes the `usa-nav__link` class when the `variant` prop is `nav`
- Add a storybook example to `Link.stories.tsx` for `<Link variant="nav">`

**Comment by haworku** [comment]
This could be accomplished by adding a `navLink` variant to the new `<Link />` #309

**Comment by SirenaBorracha** [comment]
@suzubara or @haworku could you please review and let me know if anything looks off? Otherwise I'll put up a PR. My branch: https://github.com/trussworks/react-uswds/tree/ak-feat-add-nav-variant-to-link-166

<img width="616" alt="Screen Shot 2021-02-03 at 2 49 27 PM" src="https://user-images.githubusercontent.com/16230705/106819795-27133b80-662f-11eb-85aa-ae5ef552c631.png">

**Comment by haworku** [comment]
@SirenaBorracha hello, new contributor 😄 

The ternary looks close but I think there's a change we still need. It is easier to discuss if we can comment on the code diff directly in a PR rather than here in an issue away from the code. Go ahead and open a PR from your branch. You can make a ["draft" PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and/or you can put the yellow "wip" work in progress label on it.
