### ISSUE TITLE
New component: Card

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#168]
https://designsystem.digital.gov/components/card/

**Comment by eamahanna** [comment]
## Issue Description
This goal of this issue is the add the card component to the react-uswds library. This component was added to USWDS in version 2.7.0.

## Issue Requirements
1. Create a card component that provides the ability for a user to implement the following card styles:
* Card, Card with media, Media and header first, Inset media, Exdent media, flag default, flag media on right
* Props for the card component could include: 
```
layout: 'standard' | 'flag', 
headerFirst: boolean, 
media?: React.ReactNode, 
mediaStyle?: 'inset' | 'exdent', 
flagOrientation: 'left' | 'right' (left would be the default)
```
2. Create card group component
* Props for this component could include:
```
items/cards: (this would always be card component items)
``` 
3. Create stories to display each of the styles stated above
4. Implement tests 
5. Investigate and mirror mobile UI functionality
6. Add component to exports
