### ISSUE TITLE
New Component: InputGroup

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#1692]
# Input Group

## USWDS Version

Not sure when it was introduced, but some other components (e.g. [Input Prefix and Suffix](https://designsystem.digital.gov/components/input-prefix-suffix/)) make use of this convenience component, and it seems like we should include it as well. It is very similar to `FormGroup`. 

## Description

A component that USWDS uses to group components (linked above), but not mentioned as its own exclusive component. Providing this convenience component may be nice

## Requirements (proposed)

Should be able to toggle the error state with a prop

**Prop Interface**

```JSX
interface InputGroupProps {
  children: React.ReactNode
  className?: string
  error?: boolean
}
```

## Example Implementation (proposed)

```JSX
export const InputGroup = ({
  children,
  className,
  error,
}: InputGroupProps): React.ReactElement => {
  const classes = classnames(
    'usa-input-group',
    { 'usa-input-group--error': error },
    className
  )

  return (
    <div data-testid="inputGroup" className={classes}>
      {children}
    </div>
  )
}
```

**Comment by jenbutongit** [comment]
I think `InputGroup` would be a good candidate for the API I suggested in here #1687, although it is generally quite restrictive, I'm not sure if that's how you'd like the lib to be consumed. 

`children` would only be of type `(Label | Input | InputPrefix | InputSuffix)[]` Then you would be able to control the order in which they appear using `React.Children.toArray`. I think this article touches on it, but you get the idea (hopefully?) https://www.smashingmagazine.com/2021/08/react-children-iteration-methods/. You could have extra controls for prefix/suffix so that you don't have a prefix AND suffix, or throw an error when there's an input without a label etc.
