### ISSUE TITLE
[fix] Combobox component is not fully accessible

### ISSUE THREAD

**Issue by emmastephenson** [trussworks/react-uswds#2177]
**ReactUSWDS Version & USWDS Version:**

ReactUSWDS version: 2.6.0

**Describe the bug**

The Combobox element in 2.6.0 is not fully accessible - the `Input` element of the combobox lacks a `<label>` tag.

**To Reproduce**
This problem was first noted on simplereport.gov - we use the combobox element in some of our work. I'll make a note of how to reproduce on our demo site.

1. Go to https://demo.simplereport.gov/app/register/DIS-ORG and accept the terms of service
2. Inspect the page
3. See that the `input` element on the combobox for "Preferred Language" doesn't have a `label` tag and is therefore not accessible

**Expected behavior**

All elements of the combobox should be accessible. 

**Screenshots**

This is from an accessibility scanner on our site:
<img width="643" alt="Screen Shot 2022-06-30 at 11 17 04 AM" src="https://user-images.githubusercontent.com/80282552/176749402-398b35a8-da60-4caa-8beb-0006aa780326.png">

**Additional context**

I don't believe there's a way for us to pass additional information through the combobox props specifically for the `Input` element, but please let me know if there is. I've tried adding `label` and `aria-label` to the `InputProps`, but it doesn't appear to be supported.

**Comment by emmastephenson** [comment]
If it helps to see the specific implementation, our project is open-source and the ComboBox at issue is within [`PersonForm.tsx`](https://github.com/CDCgov/prime-simplereport/blob/c2ae392ec7bba953087f9d1c9fd87ef2376e0ac6/frontend/src/app/patients/Components/PersonForm.tsx#L380-L380).

**Comment by duncan-truss** [comment]
> If it helps to see the specific implementation, our project is open-source and the ComboBox at issue is within [`PersonForm.tsx`](https://github.com/CDCgov/prime-simplereport/blob/c2ae392ec7bba953087f9d1c9fd87ef2376e0ac6/frontend/src/app/patients/Components/PersonForm.tsx#L380-L380).

Hi @emmastephenson, we appreciate you flagging this inconsistency for us and providing supporting details with the demo site and source link.

I think you're seeing that accessibility issue because your label's `htmlFor="preferred-language"` value doesn't match the `id="preferred-language-wrapper"` you provided for the ComboBox.  I saw in the devtools if I changed them to match that the accessibility warning went away.  Maybe you were trying to initially match the hidden select element's name instead of the input?  I don't know exactly which accessibility tool you're using, so let us know if that isn't a viable solution.

The team is going to discuss further enhancements to the ComboBox, in regards to labeling consistency across our components, since you pointed this out to us.

**Comment by emmastephenson** [comment]
@duncan-truss thank you for the prompt reply, and for the suggested solution! You're right, changing our `id` to `preferred-language` resolves the issue. I think you're probably right about trying to match the hidden select element, but that was before my time on the team so I'm not entirely sure 😄 

I appreciate you taking the time to discuss this further!

**Comment by duncan-truss** [comment]
> @duncan-truss thank you for the prompt reply, and for the suggested solution! You're right, changing our `id` to `preferred-language` resolves the issue. I think you're probably right about trying to match the hidden select element, but that was before my time on the team so I'm not entirely sure 😄
> 
> I appreciate you taking the time to discuss this further!

Yay, glad that was the primary issue.  It's possible our implementation has changed too over time if you weren't seeing it flagged before.
