### ISSUE TITLE
[feat] Consider using Enzyme for testing more complex React components

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#783]
[Enzyme](https://enzymejs.github.io/enzyme/)

**Does your feature request relate to a specific USWDS component?**
No

**Is your feature request related to a problem? Please describe.**
Not necessarily a _problem_, however our tests are currently limited strictly to RTL and its interaction with the DOM. For a mostly presentational library like this one, that might very well be sufficient. In the event that we want to start testing more specifically to React (props, state, or other implementation details), that's when Enzyme starts to come in handy.

**Describe the solution you'd like**
If there is agreement that Enzyme truly adds value to our tests (or that we should be testing implementation details in the first place), then we should add Enzyme as a dependency (see Enzyme documentation linked above). New unit tests, where appropriate, should rely on Enzyme for testing logic that cannot be covered by. 

Even as the person raising this "issue" I would strongly caution that Enzyme can lead to brittle tests when tightly coupled to implementation details that are subject to change. I would recommend using Enzyme sparingly, typically only where RTL alone is not sufficient.

**Describe alternatives you've considered**
Alternatively, we do not implement Enzyme. I think it is plenty reasonable to want to keep this library lean, and lean towards making sure that enzyme is not necessary for testing components used within this library. I think that is fully possible, provided they all retain low complexity.

**Comment by suzubara** [comment]
I agree that RTL should be the preferred testing solution, especially considering that this library has a heavy focus on presentational components that are primarily just rendering DOM, without explicit logic related to props & state. I will also note that Enzyme has had an [open issue for React 17 support since Aug 2020](https://github.com/enzymejs/enzyme/issues/2429) and the lack of movement on it is concerning to me.

Are there any specific use cases where we see Enzyme's testing capabilities providing new value here? I'm thinking about the ComboBox component, since that is probably our most complicated component at this time (cc @haworku ). I would also love to hear what @jenniferlynparsons thinks since I know you have lots of opinions on F/E testing :)

**Comment by jenniferlynparsons** [comment]
I agree with being cautious about implementing Enzyme on the library for all the reasons stated. RTL is the preferred testing library of the React team, which gives it a lot of credence. 
In my experience, if there appears to be a need to test implementation details it's a useful exercise to consider if there's a way to test the same thing with RTL that hasn't been uncovered. Alternately, that's where I can see integration tests become valuable. 

Reference: [Write tests. Not too many. Mostly integration.](https://kentcdodds.com/blog/write-tests)

**Comment by brandonlenz** [comment]
No need to use Enzyme at the moment. Closing.
